@startuml Test Diagram

box "SRM_Machine" #LightBlue
participant SRM_Ubuntu
participant SRM_PLC
end box

loop 10 sec
    SRM_Ubuntu->FHIR_R4_Server ++: Pull DLO Orders for all new Contaniers
    return orders
    SRM_Ubuntu->SRM_Ubuntu: Store DLO Orders
    SRM_Ubuntu->SRM_Ubuntu: Link Container by number case
end
loop for each container 
SRM_PLC->SRM_PLC: Scan container ID
SRM_PLC->SRM_Ubuntu: Read contaniner ID data
SRM_PLC->SRM_PLC: Print data in GUI
SRM_PLC->SRM_Ubuntu: Start Capture
SRM_Ubuntu->SRM_Ubuntu: Counting Test Performed
SRM_Ubuntu->SRM_Ubuntu: Best Imaged Captured
SRM_Ubuntu->SRM_PLC: Container ID is 'OK'  put in case's tray X
SRM_PLC->SRM_PLC :Put Container ID in 'OK' tray X 
SRM_PLC->SRM_PLC: Load next Contanier
end
loop 30 sec
    SRM_Ubuntu->SRM_Ubuntu: Check pending events  
    SRM_Ubuntu->SRM_Ubuntu: DICOM Generated
    SRM_Ubuntu->DICOM_Server: SEND DICOM to Cloud (POST)
    SRM_Ubuntu->SRM_Ubuntu: Sent Image
    SRM_Ubuntu->Message_Queue: Mark Contanier as Completed
end 
loop 60 sec
    SRM_Ubuntu->ELK: Send Metrics to Cloud
end 
@enduml