@startuml

node SRM_Ubuntu{

      [TwinCat]
      [ImageProcessing]
       [Controller]
     [DICOMClient]
    database SQLite    
}

node SRM_Windows_PLC {
     [GUI IIS]
          [EtherCAT]
     [PLC]
}

note right of Controller : Pull DLO data and Send events when is online

note right of ImageProcessing : Python code

cloud {
    [FHIR_Server]
    [DICOM_Server]
    [ELK]
}

[EtherCAT]--[PLC]
[GUI IIS]--[PLC]
[GUI IIS]--[TwinCat]
[GUI IIS]--[QR]
[GUI IIS]--[Controller]
[TwinCat]--[ImageProcessing]
[ImageProcessing] -- [Controller]
[ImageProcessing] -- [camera]
[Controller]--[SQLite]
[Controller]--[DICOMClient]
[Controller]--[FHIR_Server]
[Controller]--[DICOM_Server]
[Controller]--[ELK]
@enduml