@startuml

node SRM_Ubuntu{

      [TwinCat]
      [ImageProcessing]
       [Controller]
    database SQLite    
}

node SRM_Windows_PLC {
     [GUI IIS]
          [EtherCAT]
     [PLC]
}

note right of Controller : Pull DLO data and Send events when is online

note right of ImageProcessing : Python code

cloud {
    [API_Gateway]
    [laborder_service]
    [account_service]
    [DICOM_Server]
    [ELK]
}

[EtherCAT]--[PLC]
[GUI IIS]--[PLC]
[GUI IIS]--[TwinCat]
[GUI IIS]--[QR]
[GUI IIS]--[Controller]
[TwinCat]--[ImageProcessing]
[ImageProcessing] -- [Controller]
[ImageProcessing] -- [camera]
[Controller]--[SQLite]
[Controller]--[API_Gateway]
[API_Gateway]--[DICOM_Server]
[API_Gateway]--[account_service]
[API_Gateway]--[laborder_service]
[API_Gateway]--[ELK]
@enduml