@startuml

box "Kafka Cluster" #LightBlue
participant CamelConnectorProducer
participant CamelConnectorConsumerProducer
end box


CamelConnectorProducer->CamelConnectorProducer: Convert DLO to HL7 OML
CamelConnectorProducer->CamelConnectorProducer: Store HL7 OML topic_client_id

loop retry pending events
    CamelConnectorConsumerProducer->CamelConnectorConsumerProducer: Read HL7 OML topic_client_id 
    CamelConnectorConsumerProducer->LIS ++: Send HL7 OML MLLP
    return ACK
    CamelConnectorConsumerProducer->CamelConnectorConsumerProducer: Store ACK
end

@enduml