@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "interceptor (VM in DMZ)" as icp
participant "lab-order service" as lab

group cron job [every 20 seconds]
icp -> lab: getLabOrdersToExport
activate icp
activate lab
lab -> lab: get all lab orders IDs  with state <b>ACCEPTED</b>
lab --> icp: lab orders ids
deactivate lab

loop for each lab order

icp -> lab: getLabOrderAsORMById
activate lab
lab -> lab: DigitalLabOrderDto dloDto=getById(id)
lab -> lab: Convert DLO to HL7 ORM (dloDto)

lab --> icp: HL7 ORM message
deactivate lab

icp -> icp: store HL7 ORM \nmessage to SFTP server

icp -> lab: confirmLabOrderExported(id)
activate lab

lab -> lab: MarkAs<b>EXPORTED</b>(id)


lab --> icp
deactivate icp

end
end

@enduml
