@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "interceptor (VM in DMZ)" as icp
participant "integration service" as int
participant "lab-order service" as lab
participant "patient service" as pat

group cron job [every 20 seconds]
icp -> int: getLabOrdersToExport
activate icp
activate int
int -> lab: getLabOrdersWithStateReady
activate lab
lab -> lab: get all lab orders with state <b>ACCEPTED</b>
lab --> int: lab orders
deactivate lab
int --> icp: lab orders
deactivate int
loop for each lab order
icp -> int: getLabOrderAsORMById
activate int
int -> lab: getLabOrderById
activate lab

lab --> int: lab order (Dto)
deactivate lab
int -> pat: getPatientById
activate pat
pat --> int: patientAndCoverages (Dto)
deactivate pat

int -> int: Convert DLO to HL7 ORM (patient, coverages, labOrder)


int --> icp: HL7 ORM message
deactivate int
icp -> icp: store HL7 ORM \nmessage to SFTP server
icp -> int: confirmLabOrderExported
activate int
int -> lab: confirmLabOrderExported
activate lab
lab -> lab: set status <b>EXPORTED</b>
lab --> int
deactivate lab
int --> icp
deactivate int
deactivate icp

end
end

@enduml
